[firebase]
apiKey= "AIzaSyCy39kw-EGj9NcU8Vii5KAzptWfENN9bDc"
authDomain= "arte-paris-system.firebaseapp.com"
projectId= "arte-paris-system"
storageBucket= "arte-paris-system.firebasestorage.app"
messagingSenderId= "707870937788"
appId= "1:707870937788:web:8902384a9de34da3dbb6b9"
