[firebase]
type = "service_account"
project_id = "arte-paris-system"
private_key_id = "d000f8caa664c51fa7bf7b652801e1cbf4b277e9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANB...
...vb4Ciw==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@arte-paris-system.iam.gserviceaccount.com"
client_id = "107264297623842881902"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40arte-paris-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
